### PR TITLE
Added support for svg tspan element in ie9

### PR DESCRIPTION
**Pull request by mikaelgson**
Would fall through to innerHTML which apparently is handled fine in Chrome but would fail in IE9 so i added a check that uses the correct textContent property on tspan.

### CODE REVIEW

**Comment by mikaelgson** [comment]
@hhsnopek any idea when this can be merged?

**Comment by hhsnopek** [comment]
cc @inorganik

**Comment by inorganik** [comment]
I would merge this but... to be honest, and it's a lame reason, but I don't have a good conflict resolution tool. Do you guys have any suggestions?

**Comment by mikaelgson** [comment]
@inorganik Seems like the only conflict is `countUp.min.js` and thats bound to happen right?

**Comment by hhsnopek** [comment]
that's odd, is that the latest minified version?

**Comment by mikaelgson** [comment]
I think i need to sync my fork and update my PR for this to work since the minified file is versioned.

**Comment by inorganik** [comment]
Don't worry, I'm merging now.

**Pull request closed without merging**
