### PR TITLE
Adding jQuery version

### PR DESCRIPTION
**Pull request by pantrif**
Adding jQuery plugin.
I have also created a demo page here:
http://pantrif.github.io/countUp.js/

Best

### CODE REVIEW

**Comment by inorganik** [comment]
Thank you for your contribution! This needs a little bit of work - I really think this should leverage jQuery more and let params control the animation. Currently, calling this:
```js
$('.countup').CountUp(0, 94.62);
```
will fire the same animation on every element on the page that has the class `countup`. I think you ought to be able to do something like:
```html
<h1 class="countup" data-endval="123"></h1>
<h1 class="countup" data-endval="456"></h1>
<h1 class="countup" data-endval="789"></h1>
```
...where it animates to the number in the `data-endval` param.

Other issues:
- stray global var `self`;
- `callback` param is ignored in `$.fn.CountUp` definition

For what it's worth, I was able to duplicate your functionality without re-defining CountUp with this block:
```js
(function( window, $ ) {

	$.fn.CountUp = function(startVal, endVal, decimals, duration, opts,callback) {
		var cu = new CountUp(this, startVal, endVal, decimals, duration, options);
		cu.d = $(this);
		cu.printValue = function(val) { 
			cu.d.html(val) 
		};
		return cu;
	};

})(window, jQuery);	
```

I need to do the same thing for the angular plugin. Maybe you can do the same and just make CountUp a dependency?

**Comment by pantrif** [comment]
I totally agree with you to keep countUp lib as dependency.
I followed your suggestion but in order to make data-endval to work seperatelly for each element i had to store an array of instances. I havent been able to find time to create demo but here how it works:
Start:
```javascript
$(".countup").CountUp("start", 10, 162, 0, 1.5,{useEasing:true,separator:""});
```
If data-endval has been set for an element it would not take into account the endVal argument.
With callback:
```javascript
$(".countup").CountUp("start", 10, 162, 0, 1.5,{useEasing:true,separator:""},function(){alert("done")});
```
Update with argument:
```javascript
$(".countup").CountUp("update",1000);
```
Or you could do something like this if you want only one element:
```javascript
$(".countup").first().data("endval",1000);
$(".countup").CountUp("update");
```
Rest methods:
```javascript
$(".countup").CountUp("pauseResume");
$(".countup").CountUp("reset");
```


Test it yourslf to tell me if i miss anything.

Best,
Leonidas

**Comment by inorganik** [comment]
Hey, looks like this PR got a little stale. Sorry... totally forgot about it. Also, I ended up writing a quick, simple jQuery plugin and accidentally added it. Perhaps if you're interested, you could fix that one up?

**Comment by pantrif** [comment]
Hello, no problem. What needs to be fixed?

**Comment by inorganik** [comment]
Hey, thanks for being so willing. Right now I have a simple implementation that basically does this:
```js
$('#countMe').countUp(4927.3);
```
It can also accept a params object instead of just an endVal. But it is missing the ability to get params from attributes. I would like it to be able to chain methods, like this, instead of as an argument like you had:
```js
$('#countMe').pauseResumeCountUp();
$('#countMe').updateCountUp();
$('#countMe').resetCountUp();
```
If you are up for it, great! But if not, I understand.

**Comment by pantrif** [comment]
I have already implemented this behaviour. Just accept the pull request and you are set.
https://github.com/pantrif/countUp.js/blob/master/countUp.jquery.js

**Comment by inorganik** [comment]
There are conflicts in your branch, so you need to pull master and merge it into your branch. Then I'll merge. Thanks.

**Comment by pantrif** [comment]
Ok Jamie I think we are ok now! After you test it make the merge (i say in a previous post how to use options).

**Comment by pantrif** [comment]
Hello Jamie, are you planning to accept this pull request?

**Comment by inorganik** [comment]
Sorry, been very busy. I will check it soon.

**Comment by inorganik** [comment]
Hi, Sorry for the long delay on this. Looks like you implemented the functions as string arguments:
```js
$(".countup").CountUp("reset");
```
But I had requested that they each be their own methods:
```js
$('#countMe').resetCountUp();
```
Also, methods should start with a lowercase letter - `countUp` not `CountUp`. The CountUp class in countUp.js is uppercase because it is a "class" - or as close as you can get to a class in javascript. But methods should start with lowercase.

In addition the `countUp()` method should keep it's existing functionality of passing the endVal like 
```js
$('#countMe').countUp(4927.3);
```
So that no existing implementations get broken by the change. Omitting the argument would use the `data-endVal` attribute property of the element in the selector.

I understand you may not want to put forth the effort to do these things, and if not, that's ok. But to merge them here I would like those changes.

Thanks,
Jamie

**Comment by pantrif** [comment]
Hello, unfortunately right now i have not the time to put more effort on this. So feel free to reject this pull request. 

Best,
Leonidas

**Comment by simonmacfadyen** [comment]
What a shame, this seemed so close.

**Pull request closed without merging**
