### PR TITLE
New method: update(num)

### PR DESCRIPTION
**Pull request by aludvigsen**
Added possibility to update existing counter and animate to a new number, without the need to create a new instance.

Example: 

```javascript
numAnim.update(135);
```

### CODE REVIEW

**Comment by inorganik** [comment]
Nice one, thanks

**Comment by sahat** [comment]
This needs to be documented. Pretty useful method.

**Comment by aludvigsen** [comment]
@sahat, I created a PR for the updated documentation and demo now.

**Comment by sahat** [comment]
Thanks @aludvigsen !

**Pull request merged**
