### PR TITLE
angular-countUp: support data binding in directive attrs

### PR DESCRIPTION
**Pull request by Vivihung**
1. Support data binding in directive attrs. 
2. Remove console logs for counts. 
3. Add reanimate-on-click attr to config if reanimate on click event

### CODE REVIEW

**Comment by Vivihung** [comment]
Usage example
###### Html
```html
<span count-up
           end-val="number"
           decimals="numberDecimal"
           duration="numberAnimationDuration"
           reanimate-on-click="false"></span>
```

###### JavaScript
```javascript
$scope.number=12;
$scope.numberDecimal=1;
$scope.numberAnimationDuration=3;
```

**Comment by inorganik** [comment]
Hi Vivien - this looks great - just a couple things:

1. Please run `gulp`, so that the minified version of the angular module is created in the "dist" folder - it also copies the unminified version there. It should be pretty easy - just `cd` to the countUp directory, then run `npm install` and then `gulp` in your console, and you'll be good to go.
2. I would like reanimate on click to remain the default behavior

Once you make those changes I can merge.

Thanks!

**Comment by Vivihung** [comment]
I hit errors when run gulp. Trying to resolve it. Any hint will be helpful.

[12:45:27] Warning: gulp version mismatch:
[12:45:27] Global gulp is 3.9.0
[12:45:27] Local gulp is 3.8.11
[12:45:28] Using gulpfile ~\documents\GitHub\countUp.js\countUp.js\gulpfile.js
[12:45:28] Starting 'clean'...
[12:45:28] Finished 'clean' after 3.02 ms
[12:45:28] Starting 'umd'...

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (C:\Users\vivihung\documents\GitHub\countUp.js\countUp.js\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (C:\Users\vivihung\documents\GitHub\countUp.js\countUp.js\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (C:\Users\vivihung\documents\GitHub\countUp.js\countUp.js\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2025:9)
    at token_error (eval at <anonymous> (C:\Users\vivihung\documents\GitHub\countUp.js\countUp.js\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2033:9)
    at unexpected (eval at <anonymous> (C:\Users\vivihung\documents\GitHub\countUp.js\countUp.js\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2039:9)
    at semicolon (eval at <anonymous> (C:\Users\vivihung\documents\GitHub\countUp.js\countUp.js\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2059:43)
    at simple_statement (eval at <anonymous> (C:\Users\vivihung\documents\GitHub\countUp.js\countUp.js\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2239:73)
    at eval (eval at <anonymous> (C:\Users\vivihung\documents\GitHub\countUp.js\countUp.js\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2112:19)
    at eval (eval at <anonymous> (C:\Users\vivihung\documents\GitHub\countUp.js\countUp.js\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2072:24)
    at block_ (eval at <anonymous> (C:\Users\vivihung\documents\GitHub\countUp.js\countUp.js\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2352:20)

**Comment by inorganik** [comment]
run `npm update`

**Comment by Vivihung** [comment]
I figure out the error comes from my code change which uses ES6 "let".
I'm not sure if you would like to update gulp config to support ES6. [ [Reference link] ](https://stephensauceda.com/es6-in-your-gulp-tasks/)
So I just replace it with "var" for now.

I will close this request and squash all my commits into one change. Then send another pull request.

Here is another reference about how to investigate gulp task errors. Node will hide the original error with helpless message shown above, with this code in gulpfile.js, you can see the error details (filename, line#) in console.
[[How to debug gulp build errors]](https://github.com/gulpjs/gulp/blob/master/docs/recipes/combining-streams-to-handle-errors.md#combining-streams-to-handle-errors)

**Pull request closed without merging**
