### PR TITLE
Custom easing functions

### PR DESCRIPTION
**Pull request by mmieluch**
Hi there, I extended the plugin so that now users can specify their own easing functions.

Changes are backwards compatible and if user doesn't specify `easingFn` option plugin will fall back automatically to original `easeOutExpo`.

To use custom easing function all the user has to do is to pass the easing closure as an option:

```js
var easeOutCubic = function (t, b, c, d) {
    var ts = (t /= d) * t;
    var tc = ts * t;
    return b + c * (tc + -3 * ts + 3 * t);
}

var options = {
    easingFn: easeOutCubic
};
```

Changes include documentation updates (both README and HTML demo file).

Let me know what you think :)

Cheers!

### CODE REVIEW

**Comment by inorganik** [comment]
Thanks!

**Comment by mmieluch** [comment]
Glad to be of help.

**Comment by inorganik** [comment]
For the sake of simplicity in the demo, I will probably remove the textarea showing the easing function; it's confusing that it's readonly - I kept trying to focus it and thought it was broken.

**Comment by mmieluch** [comment]
No problem. I could do it for you and send you a PR tomorrow.

**Comment by inorganik** [comment]
Oh that would be sweet. Can you just have the "custom easing" heading, and the select. Then have `createCountUp()` fire onChange.

**Comment by mmieluch** [comment]
No problem, I see how the textarea could be confusing. Cheers!

**Pull request merged**
