### PR TITLE
add user defined function to define the result as you like

### PR DESCRIPTION
**Pull request by pslean**
With this function, I can defined the result like this:
image

### CODE REVIEW

**Comment by pslean** [comment]
@inorganik Please help to review the code. thanks.

**Comment by inorganik** [comment]
Hi, thank you for your pull-request. I'm unclear on what you are demonstrating with the image above - you can easily style text like that with css without any modifications to countUp.js. 

But even if you needed a custom function, there is already an optional formatting function that can be passed in the options as you know. If you need the default formatNumber function to run in addition to some custom code you are doing, simply copy that function into your custom function, but replace the references to vars defined in the CountUp instance. Then pass it as the optional formatting function.

Let me know if I am missing some use-case, else I will close this PR. Thanks.

**Comment by pslean** [comment]
In my user-case, I want to use images to show my numbers. If I pass the formattingFn to format my number, I will do the same thing in your self.formatNumber funtion firstly, and then change my numbers to images in css. After we get the result from the formattingFn function, we can use the udfNumber function to format the result. Or I will do duplicate work in the self.formatNumber. This is my code:
image
In this case, I am using the default formatNumber function to format my numbers and then change them to images.

**Comment by inorganik** [comment]
Yes, I think that's what you should do. But even better would be to not use images at all and style your text with CSS. It's pretty easy to create the glow effect with text-shadow. Here's a generator: http://css3gen.com/text-shadow/

Closing this one... good luck.

**Pull request closed without merging**
