### PR TITLE
Fix scrollspy reset when scrolling above the countUp

### LINKED ISSUE #294: ScrollSpy does not reset countUp when the user scrolls back to the top of the page
```
[X] Bug
[ ] Feature request

CountUp.js version: 2.3.2

```

## Description

1. Activate scrollSpy by passing it to options : 
`this.countUp = new CountUp(dom, this.endVal, {enableScrollSpy : true})`

2. Scroll until you can see the countUp : it starts counting (expected behaviour)
3. Continue scrolling : when the countUp disappears, the countUp resets (expected behaviour)
4. Now, scroll back to the top of the page and scroll again until you can see the countUp again : the countUp has not been reset

This code should do the trick ([line 106 of ./src/countUp.ts](https://github.com/inorganik/countUp.js/blob/master/src/countUp.ts#L106)) : 
```
handleScroll(self: CountUp): void {
	if (!self || !window || self.once) return;
	
	const bottomOfScroll = window.innerHeight +  window.scrollY;
	const rect = self.el.getBoundingClientRect();
	const topOfEl = rect.top + window.pageYOffset
	const bottomOfEl = rect.top + rect.height + window.pageYOffset;
	
	if (bottomOfEl < bottomOfScroll && bottomOfEl >  window.scrollY && self.paused) {
		// in view
		self.paused = false;
		setTimeout(() => self.start(), self.options.scrollSpyDelay);
		if (self.options.scrollSpyOnce)
		self.once = true;
	} else if (
          (window.scrollY > bottomOfEl || topOfEl > bottomOfScroll) &&
          !self.paused
        ) {
		// out of view
		self.reset();
	}
}
```

### PR DESCRIPTION
**Pull request by paidge**
## I'm submitting a...

```
[X] Bug Fix
[ ] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [X] Test your changes
- [X] Followed the build steps

## Description

Fix #294

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by inorganik** [comment]
Can you please resolve conflicts, then i can pull and test?

**Comment by inorganik** [comment]
You should be able to just merge master, then rebuild

**Comment by paidge** [comment]
I think that is ready for testing

**Comment by inorganik** [comment]
Just getting around to this, and looking at the diffs something is messed up, because it is showing my changes as additions in your PR. I could easily add your change, but I would like you to get credit for it. 

Can you please try to re-merge master using the [instructions here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-command-line)? We should only see your changes as additions.

**Comment by inorganik** [comment]
@paidge yes except your formatting is causing whitespace changes. Please match the formatting - spaces not tabs, only 2 spaces/tab

**Comment by paidge** [comment]
sorry i dont understand. I ran `npm run lint`. How could I resolve this issue ?

**Comment by paidge** [comment]
I saw that line 123 was not correctly idented. I corrected manually. Is it better ?

**Comment by inorganik** [comment]
Look at [this diff](https://github.com/inorganik/countUp.js/pull/295/files#diff-b95367e335803cc0effa75e5982d6886201b96e1ac0473c8ead6112283728aaf) and look at the indents. You are using 4-space tab indents, but the rest of the file is using 2-space indents. You've only changed line 122-125, but lines 108-129 have changes because of the whitespace. Also lines 108 and 129 have no indent, when they should have an indent. You've also added several empty lines.

Once you get it where only lines 122-125 have a change (minus the empty lines), you'll know you've fixed it.

**Comment by paidge** [comment]
Strange. I replaced manually tabs with spaces. This should be ok now.

**Comment by inorganik** [comment]
Look at the diff again. Still whitespace changes, because the indent for the function is gone - this should be visible as you scroll the code in your IDE. Also the empty lines still there. 

Drop another comment after you've pushed, and doubled checked the diff in the "files changed" tab of this PR. It should only have green on the four lines you changed.

**Comment by paidge** [comment]
sry. I checked the diff and indentation should be right

**Comment by inorganik** [comment]
That'll work, thanks for sticking with it!

**Pull request merged**
