### PR TITLE
Add Arabic & Farsi Digits Output to Options

### PR DESCRIPTION
**Pull request by Pourbahrami**
**digitsConvert** function allows outputting digits in Arabic and Farsi by setting option **digits**.

### CODE REVIEW

**Comment by inorganik** [comment]
Thank you for this - will merge as soon as I have time (need to increment version number in package.json and clean up some spacing for consistency ).

**Comment by inorganik** [comment]
Looking into this, I decided to rename "digits" to "numerals", since these are numeral systems.

I couldn't find any standardized ISO codes for numeral systems, because I think numerals are lumped in with language, so language codes determine which numerals are used

What's the use-case for needing to specify a numeral system? If your browser language is set to `ar-*`, wouldn't use the eastern arabic numerals ("١٢٣٤")? 

I'm also wondering about using `en` for "1234". It's confusing but those are [Arabic numerals](https://en.wikipedia.org/wiki/Arabic_numerals). Arabic numerals are used for lots of languages besides English. Should we leave the codes as they are anyway? `en`, `ar`, `fa`?

**Comment by Pourbahrami** [comment]
You're right. Maybe we should get a ten elements array in `options` for custom output characters instead of language codes?

`'chars': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] // to outputting bfd as 153`

**Comment by inorganik** [comment]
Good suggestion, this is now implemented in v1.9.0, and you can also [demo it](http://inorganik.github.io/countUp.js/).

**Pull request merged**
