### PR TITLE
Improvements

### LINKED ISSUE #35: Component
I attempted to use component with countUp, but I can't find it.
I believe countUp needs to be registered

### LINKED ISSUE #43: Package name
When using component the name of the package corresponds with the name that you require. The current issue with the name of the package is that `countup.js` has a dot in it. Which doesn't follow the naming conventions for component. My suggestion is to change the name within `component.json` and `bower.json` so they correspond. I'm thinking the name should be `countup`

People will still be able to search for the package with the keywords and find this as easily as they did before, and we don't have to change the name of the repo; just the name defined in `component.json` and `bower.json` :grinning: 

example - TJ uses `page.js` as the name, but has the reference name as `page`:
[visionmedia/page](https://github.com/visionmedia/page.js)
`page = require('page');`

### PR DESCRIPTION
**Pull request by hhsnopek**
- adds build for amd/umd support via gulp
- adds npm support
- moves builds to `dist`, separating source from amd/umd wrapper
- adds `.editorconfig` to normalize all editors for future updates

closes #35
closes #43

### CODE REVIEW

**Comment by hhsnopek** [comment]
I was unsure what you'd like to include in the `CHANGELOG.md` so I left that open for your changes

**Comment by hhsnopek** [comment]
@inorganik I just realized in #43 and #35 that I referenced the wrong #. Sorry about that!

**Comment by hhsnopek** [comment]
ping @inorganik - lemme know if there's anything I can help clarify in this PR

**Comment by inorganik** [comment]
Thanks Henry, looks like you put a fair amount of time into this, I appreciate it. Well, I just merged a PR that makes this lib support AMD, which means it also supports UMD. I see though that you created a distribution folder, and added a gulpfile and package.json file. 

Here's what I would like to do... basically just merge the gulpfile and package.json. I can't justify a new release just for adding the gulpfile, that's really the only thing from this PR that's changed from the last release. The readme changes are very minimal and arbitrary, I don't think they're necessary. Also, I'd rather not have 2 copies of countUp.js, in both the root and dist folders. I'd like to just have 1 in the root. Most people when they submit a PR forget to update the minified version, let alone another copy of countUp. 

I hope that's ok with you, I think the gulpfile and package.json would be nice to include.

**Comment by hhsnopek** [comment]
@inorganik you some good points, let me clarify the changes.

1. When updating the library you run `npm run build` which will build both versions (minified/unminified). This pulls out all the middle work you had to previously do, which was manually updating both.

2. The `countUp.js` located at the root of the project is the source code. The other versions located in `/dist` is what the consumers/users should be using. As best practice you should separate the source code from the UMD wrapper. This is so that when someone does modify the source they don't tamper with the wrappers and the wrappers stay up to date.  What we really should do is move `/countUp.js` to `/lib/index.js`, but I neglect that because I don't find it necessary. 

3. AMD support != UMD support, UMD supports both AMD (like require.js) and Common.js (like browserify and component). The previous commit only supports AMD which doesn't support Common.js The gulpfile automates the wrapping of the UMD and keeps everything up to date. As stated in point 2 this is a best practice.

4. The markdown changes are very minimal and arbitrary. This just cleans up, beautifies and tidy's up the markdown with [tidy-markdown](//github.com/slang800/tidy-markdown).

**Comment by inorganik** [comment]
The problem I have with using this build system (although I already use gulp) for the repo is that it forces anyone using this lib to use it... this repo has become fairly bloated already, I'd love to keep it as trim and simple as possible. It's a small component, I would suspect people will copy and paste the bits they need and integrate them into their code base. Sorry to be stubborn on this...

Could you please elaborate why AMD doesn't equal UMD support? How are they different? From what I could find the wrapper is the same.

**Comment by hhsnopek** [comment]
Anyone using the repo doesn't have to use gulp unless they're developing CountUp. Pardon me If i'm wrong, but I don't think you understand how downloading these libraries works with Bower, Component & NPM. We have `.npmignore`, `bower.json` and `component.json` which defines what will and won't be available when downloading the library. No one will get `gulpfile.js`, they will only get what we want them to have. No bloat found at all. Actually all the "bloat" I've added is really a convenience for developers. It makes it less time consuming for developers, they don't have to worry about screwing with `UMD` or having to build and uglify the project. They can now just `gulp build` and it will build both with UMD support.

CommonJS vs AMD vs Global syntax: <http://stackoverflow.com/a/14033636/1576404>
UMD: <https://github.com/umdjs/umd#umd-universal-module-definition>

**Comment by inorganik** [comment]
Hey Henry, you are quite right, I haven't used javascript package managers before. Tell you what. I made some minor changes to countUp.js to clean up some code... if you could please merge those to your codebase, and update the README to better describe how one would install with said build system, I'll merge. Thanks for explaining stuff to me and all your contributions!

**Comment by hhsnopek** [comment]
@inorganik this is all set

**Comment by hhsnopek** [comment]
this just requires a changelog update, if you could take care of that @inorganik

**Comment by inorganik** [comment]
Woohoo!, thanks Henry. I updated the version to 1.5.2 and I will make a new release.

**Comment by hhsnopek** [comment]
wait!

**Comment by hhsnopek** [comment]
nvm haha - thought it should be `1.6.0` but since there's no breaking changes you're right

**Comment by hhsnopek** [comment]
I could have also removed my commit that did a minor version bump in my PR :wink:

**Comment by inorganik** [comment]
hehe you scared me. Yea, no code changes.

**Pull request merged**
