### PR TITLE
FrameVal Parent Scope Availability

### PR DESCRIPTION
**Pull request by alexgurrola**
The logic here is quite simple and allows for us to use the counter to also animate other angular items on the page (i.e. overlay width) with a solid screen refresh rate while updating.

### CODE REVIEW

**Comment by inorganik** [comment]
Hey @alexgurrola would you mind syncing your branch up with master so I can merge this?

**Comment by alexgurrola** [comment]
@inorganik All synced!

**Comment by alexgurrola** [comment]
@inorganik Synced and no conflicts now.  👍

**Comment by inorganik** [comment]
Hey @alexgurrola, sorry but upon further examination of your PR, I decided not to merge this, here's why:
- you're calling your step function on every frame regardless if the dev passed a `countInstance` in their instance
- you're calling `$parse` on every frame in your step function, which concerns me performance-wise
- you're calling $digest on a parent scope, which may or may not apply to a related animation the dev is doing - it's too specific
- you're calling $digest extremely often by calling it in the step function (up to 60x/second) which is almost guaranteed to interrupt a digest in progress and throw console errors. 

It might work as a good custom solution for what you are doing but I don't think this is boilerplate or safe enough to merge. Thanks anyway.

**Pull request closed without merging**
