### PR TITLE
Add "isCounting" property

### PR DESCRIPTION
**Pull request by mizzos**
In my example I needed to check whether the counter is still in the process of counting or not.
I found it helpful to trigger the counter when it moves to the viewport.

### CODE REVIEW

**Comment by inorganik** [comment]
Curious about this use-case. I've used count-up with scroll spy ([see example](http://inorganik.github.io/angular-scroll-spy/)) and not needed an isCounting property. Can you please elaborate how you would use it?

**Comment by mizzos** [comment]
Your example is suitable for Angular applications. I don't use Angular for my projects.
I must confess the event `elementFirstScrolledIntoView` is pretty good and exacly what I need.

However, my self-made scroll event listener fires every time the page is scrolled:
```javascript
var oldFunction = document.onscroll;
        var newFunction = function () {
            counterFunction();
            if (typeof( oldFunction ) == 'function')
                oldFunction();
        };
        document.onscroll = newFunction;
```

In `counterFunction` I need to be able to check whether the counter is still in the process of counting and the desired element is in the viewport:
```javascript
function counterFunction() {
    if ((!counterCustomers.isCounting) && isScrolledIntoView($("#counterCustomers"))) {
        counterCoustomers.start();
    }
}
```
That would be my usecase.

**Comment by inorganik** [comment]
My example is angular, but all angular does in that directive is give us a reference to the element. Other than that it's just regular 'ole js. I'm not trying to be a pain– but if the counting element is not scrolled into view, it wouldn't matter whether it was counting or not because it was out of view. Therefore you can always start the animation as the element is scrolled into view.

**Comment by inorganik** [comment]
Closing this since I am releasing a major update - 2.0

**Pull request closed without merging**
